In [65]:
#importing necessary  libraries
import  numpy as np

In [66]:
np.__version__

'1.18.5'

## NumPy
NumPy is optimized for carrying out math operations on array-like structures.

In [67]:
# defining array from list or other py iterables
arr1 = np.array([1,2,3,4,5])
arr2 = np.array({1,2,3,4,5})
arr3 = np.array((1,2,3,4,5))

In [68]:
type(arr1),type(arr2), type(arr3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [69]:
arr1.dtype # datatype

dtype('int32')

In [70]:
arr1.ndim #array dimension

1

In [71]:
arr1.size

5

In [72]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr4.ndim #array dimension

2

In [74]:
arr4.size #total number of element in the array

9

In [75]:
arr4.shape # total_row * total_column

(3, 3)

### Array Slicing

In [76]:
arr4[1] #selecting array second row

array([4, 5, 6])

In [77]:
arr4[1,2]

6

In [78]:
arr4[...,2]  #third column

array([3, 6, 9])

In [79]:
arr4[:,2]   #third column

array([3, 6, 9])

In [80]:
#negative slicing
arr4[-1] #last row corresponding to third row here

array([7, 8, 9])

In [81]:
arr4[0::2] #first and last row

array([[1, 2, 3],
       [7, 8, 9]])

In [82]:
arr4[2,[1,2]] # third row, and second & third columns elements

array([8, 9])

In [83]:
arr4[2,1:] # third row, and  from second to last columns elements

array([8, 9])

In [84]:
np.array([1.1,2.2,3.3]).astype('i') #defining an array as another type

array([1, 2, 3], dtype=int32)

In [85]:
x = np.array([1.1,2.2,3.3],dtype='i')   #defining an array with dtype
x

array([1, 2, 3], dtype=int32)

In [86]:
x.astype('bool')  #astype

array([ True,  True,  True])

#### difference between copy and view

In [87]:
y = x.copy()
z = x.view()
y.base ,z.base 
#y.base returns None bacause it has no base. copy returns a new array with same elements

(None, array([1, 2, 3], dtype=int32))

In [88]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
arr5 = arr4.reshape(9,1) # reshape the array to another shape
arr5

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [90]:
arr5.base

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
arr5[3] = 99
arr4  #arr4 is also affected by assignment operation in arr5

array([[ 1,  2,  3],
       [99,  5,  6],
       [ 7,  8,  9]])

#### ravel vs flatten

In [92]:
arr6 = arr4.flatten()
arr6

array([ 1,  2,  3, 99,  5,  6,  7,  8,  9])

In [93]:
arr6.base  #similar to view

In [94]:
arr7 = arr4.ravel()
arr7

array([ 1,  2,  3, 99,  5,  6,  7,  8,  9])

In [95]:
arr7.base  #similar to copy

array([[ 1,  2,  3],
       [99,  5,  6],
       [ 7,  8,  9]])

In [96]:
xz = np.arange(0,20).reshape(4,5)
xz

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [97]:
%%timeit
result=[]
for a in xz:
    for i in a:
        result.append(i)
result
#this is to show that we will need multiple for loop to iterate through multidimentional array

12.4 µs ± 1.49 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [98]:
%%timeit
result=[]
for i in xz.flatten():
    result.append(i)
result

9.5 µs ± 1.3 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [99]:
%%timeit
#nditer allow us easily access each element of multidimentional array 
#it is highly optimized for this sort of iteratio
result=[]
for i in np.nditer(xz):
    result.append(i)
result

6.06 µs ± 395 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [100]:
#ndenumerate # simlar to python enumerate that returns index,element pair
result=[]
for i,j in np.ndenumerate(xz):
    result.append([i,j])
result[:3]

[[(0, 0), 0], [(0, 1), 1], [(0, 2), 2]]

In [101]:
x1 = np.arange(1,5).reshape(2,2)
x2 = np.arange(5,9).reshape(2,2)
print(f'x1={x1} \n\n x2={x2}')

x1=[[1 2]
 [3 4]] 

 x2=[[5 6]
 [7 8]]


In [102]:
np.concatenate((x1,x2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [103]:
np.concatenate((x1,x2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [104]:
np.stack((x1,x2)) #stack result into higher dimension than the constituent arrays

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [105]:
np.stack((x1,x2), axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [106]:
np.hstack((x1,x2)) #same as np.concatenate((x1,x2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [107]:
np.vstack((x1,x2)) #same as np.concatenate((x1,x2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [108]:
np.dstack((x1,x2)) 

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

#### Array Splitting

In [109]:
arr1

array([1, 2, 3, 4, 5])

In [110]:
np.array_split(arr1,2) #splitting array 1 into 2

[array([1, 2, 3]), array([4, 5])]

In [111]:
np.array_split(arr1,4)
#note : if array_split operation has to split an which can't have equal elements, it adjust the accordingly 

[array([1, 2]), array([3]), array([4]), array([5])]

In [112]:
arrx= np.array([[ 1,  2],
                [ 3,  4],
                [ 5,  6],
                [ 7,  8],
                [ 9, 10],
                [11,12]])
arrx

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [113]:
np.array_split(arrx,2,axis=0)

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [114]:
np.array_split(arrx,2,axis=1)

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]])]

In [115]:
np.array_split(arrx,3,axis=1)

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]]),
 array([], shape=(6, 0), dtype=int32)]

#### np.where()

In [116]:
arr1

array([1, 2, 3, 4, 5])

In [117]:
np.where(arr1>2) #returns index where the condition is True

(array([2, 3, 4], dtype=int64),)

In [118]:
np.where(arr1>2,True, False) #using where like a tenary operator or if statement

array([False, False,  True,  True,  True])

#### np.newaxis()

In [119]:
arr1

array([1, 2, 3, 4, 5])

In [120]:
arry = arr1[:,np.newaxis]
arr1.shape, arry.shape

((5,), (5, 1))

In [121]:
arr2 = np.array([[9,20],[13,4]])
arr2

array([[ 9, 20],
       [13,  4]])

In [122]:
arr2.sort(axis=0)  #this operation sort inplace
print(arr2)

[[ 9  4]
 [13 20]]


In [123]:
arr2.sort(axis=1) #this operation sort inplace
print(arr2)


[[ 4  9]
 [13 20]]


In [124]:
np.sort(arr2,axis=1) #this operation returns the sorted array, the original array won't be modified #pure_function

array([[ 4,  9],
       [13, 20]])

In [125]:
np.sort(arr2,axis=0)

array([[ 4,  9],
       [13, 20]])

#### np.diag()

In [126]:
np.diag([1,2,3,4]) #creates diagonal matrice

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [127]:
np.diag([1,2,3,4],1) #defines a matrix whose elements are above the leading diagonal

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [128]:
np.diag([1,2,3,4],-1) #defines a matrix whose elements are below the leading diagonal

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])