In [ ]:
#importing necessary  libraries
import  numpy as np

In [ ]:
np.__version__

## NumPy
NumPy is optimized for carrying out math operations on array-like structures.

In [ ]:
# defining array from list or other py iterables
arr1 = np.array([1,2,3,4,5])
arr2 = np.array({1,2,3,4,5})
arr3 = np.array((1,2,3,4,5))

In [ ]:
type(arr1),type(arr2), type(arr3)

In [ ]:
arr1.dtype # datatype

In [ ]:
arr1.ndim #array dimension

In [ ]:
arr1.size

In [ ]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4

In [ ]:
arr4.ndim #array dimension

In [ ]:
arr4.size #total number of element in the array

In [ ]:
arr4.shape # total_row * total_column

### Array Slicing

In [ ]:
arr4[1] #selecting array second row

In [ ]:
arr4[1,2]

In [ ]:
arr4[...,2]  #third column

In [ ]:
arr4[:,2]   #third column

In [ ]:
#negative slicing
arr4[-1] #last row corresponding to third row here

In [ ]:
arr4[0::2] #first and last row

In [ ]:
arr4[2,[1,2]] # third row, and second & third columns elements

In [ ]:
arr4[2,1:] # third row, and  from second to last columns elements

In [ ]:
np.array([1.1,2.2,3.3]).astype('i') #defining an array as another type

In [ ]:
x = np.array([1.1,2.2,3.3],dtype='i')   #defining an array with dtype
x

In [ ]:
x.astype('bool')  #astype

#### difference between copy and view

In [ ]:
y = x.copy()
z = x.view()
y.base ,z.base 
#y.base returns None bacause it has no base. copy returns a new array with same elements

In [ ]:
arr4

In [ ]:
arr5 = arr4.reshape(9,1) # reshape the array to another shape
arr5

In [ ]:
arr5.base

In [ ]:
arr5[3] = 99
arr4  #arr4 is also affected by assignment operation in arr5

#### ravel vs flatten

In [ ]:
arr6 = arr4.flatten()
arr6

In [ ]:
arr6.base  #similar to view

In [ ]:
arr7 = arr4.ravel()
arr7

In [ ]:
arr7.base  #similar to copy

In [ ]:
xz = np.arange(0,20).reshape(4,5)
xz

In [ ]:
%%timeit
result=[]
for a in xz:
    for i in a:
        result.append(i)
result
#this is to show that we will need multiple for loop to iterate through multidimentional array

In [ ]:
%%timeit
result=[]
for i in xz.flatten():
    result.append(i)
result

In [ ]:
%%timeit
#nditer allow us easily access each element of multidimentional array 
#it is highly optimized for this sort of iteratio
result=[]
for i in np.nditer(xz):
    result.append(i)
result

In [ ]:
#ndenumerate # simlar to python enumerate that returns index,element pair
result=[]
for i,j in np.ndenumerate(xz):
    result.append([i,j])
result[:3]

In [ ]:
x1 = np.arange(1,5).reshape(2,2)
x2 = np.arange(5,9).reshape(2,2)
print(f'x1={x1} \n\n x2={x2}')

In [ ]:
np.concatenate((x1,x2))

In [ ]:
np.concatenate((x1,x2), axis=1)

In [ ]:
np.stack((x1,x2)) #stack result into higher dimension than the constituent arrays

In [ ]:
np.stack((x1,x2), axis=1)

In [ ]:
np.hstack((x1,x2)) #same as np.concatenate((x1,x2), axis=1)

In [ ]:
np.vstack((x1,x2)) #same as np.concatenate((x1,x2), axis=0)

In [ ]:
np.dstack((x1,x2)) 

#### Array Splitting

In [ ]:
arr1

In [ ]:
np.array_split(arr1,2) #splitting array 1 into 2

In [ ]:
np.array_split(arr1,4)
#note : if array_split operation has to split an which can't have equal elements, it adjust the accordingly 

In [ ]:
arrx= np.array([[ 1,  2],
                [ 3,  4],
                [ 5,  6],
                [ 7,  8],
                [ 9, 10],
                [11,12]])
arrx

In [ ]:
np.array_split(arrx,2,axis=0)

In [ ]:
np.array_split(arrx,2,axis=1)

In [ ]:
np.array_split(arrx,3,axis=1)

#### np.where()

In [ ]:
arr1

In [ ]:
np.where(arr1>2) #returns index where the condition is True

In [ ]:
np.where(arr1>2,True, False) #using where like a tenary operator or if statement

#### np.newaxis()

In [ ]:
arr1

In [ ]:
arry = arr1[:,np.newaxis]
arr1.shape, arry.shape

In [ ]:
arr2 = np.array([[9,20],[13,4]])
arr2

In [ ]:
arr2.sort(axis=0)  #this operation sort inplace
print(arr2)

In [ ]:
arr2.sort(axis=1) #this operation sort inplace
print(arr2)


In [ ]:
np.sort(arr2,axis=1) #this operation returns the sorted array, the original array won't be modified #pure_function

In [ ]:
np.sort(arr2,axis=0)

#### np.diag()

In [62]:
np.diag([1,2,3,4]) #creates diagonal matrice

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [63]:
np.diag([1,2,3,4],1) #defines a matrix whose elements are above the leading diagonal

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [64]:
np.diag([1,2,3,4],-1) #defines a matrix whose elements are below the leading diagonal

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])